[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "estacao-raspberry"
version = "0.1.0"
description = "Projeto base para estação meteorológica com Raspberry Pi"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Seu Nome" }]
license = { text = "MIT" }

[project.optional-dependencies]
devel = [
  "pytest>=8.0.0",
  "ruff>=0.6.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
